app = "boardlink"
primary_region = "ewr"

[build]
  dockerfile = "Dockerfile"

[[services]]
  internal_port = 8082
  protocol = "tcp"
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.http_checks]]
    interval = 10000
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"
    timeout = 2000
